name: .NET CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DotNet/src/ExampleWebApp

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore ExampleWebApp.sln

      - name: Build
        run: dotnet build ExampleWebApp.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ../ExampleWebApp.Tests/ExampleWebApp.Tests.csproj --configuration Release --no-build --verbosity normal
